# Generated by Django 3.2.4 on 2021-06-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='screenshot',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
