# Generated by Django 3.2.4 on 2021-06-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210606_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='screenshot',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d'),
        ),
    ]
